### ISSUE TITLE
Make read() and write() functions in Cache.FileSystem async

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1252] opened 2023-11-17 13:45 UTC
Both SmartContract.compile() and Transaction.prove() are async functions but read and write functions of Cache.FileSystem are sync functions.

Getting prover keys from AWS S3 or CDN directly is impossible, as we need to call async functions to download prover keys.
The solution now is pre-downloading prover keys, even those that will not be needed later, and providing to compile() Cache object referring to the pre-downloaded prover keys.

Making those functions async will allow dynamic loading of the prover keys from Netlify of AWS CDN, thus significantly improving user experiences.

**Comment by mitschabaude** [comment] 2024-10-14 10:31
dupe of #1610, should be closed @Trivo25

**Closed** 2024-10-14 10:58 UTC
