### ISSUE TITLE
0.15.0 gives Argument of type PublicKey is not assignable to parameter of type PublicKey errors

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1317] opened 2023-12-13 17:13 UTC
When switching from 0.14.2 to 0.15.0, I received many errors, like
```
/Users/mike/Documents/DeFi/MinaNFT/minanft-api/src/api/mint.ts (61,53): Argument of type 'import("/Users/mike/Documents/DeFi/MinaNFT/minanft-api/node_modules/o1js/dist/node/lib/signature").PublicKey' is not assignable to parameter of type 'import("/Users/mike/Documents/DeFi/MinaNFT/minanft-api/node_modules/minanft/node_modules/o1js/dist/node/lib/signature").PublicKey'.
...
/Users/mike/Documents/DeFi/MinaNFT/minanft-api/src/storage/filedata.ts (33,5): Type 'import("/Users/mike/Documents/DeFi/MinaNFT/minanft-api/node_modules/o1js/dist/node/lib/field").Field' is not assignable to type 'import("/Users/mike/Documents/DeFi/MinaNFT/minanft-api/node_modules/minanft/node_modules/o1js/dist/node/lib/field").Field'.
  Property '#private' in type 'Field' refers to a different member that cannot be accessed from within type 'Field'.
```
for all types like PublicKey, PrivateKey, and Field.
I'm importing o1js in minanft library, and then I import in the backend both minanft library and o1js. 
It worked fine before 0.15.0 and started working again when I downgraded from 0.15.0 to 0.14.2. 
I see that there was some refactoring of Provable made in 0.15.0, maybe it gives this effect.

**Comment by mitschabaude** [comment] 2023-12-14 14:55
@dfstio I'm looking into this. I think the main culprit is that you have a package dependency (`minanft`) which uses an older o1js version.

We usually recommend to have o1js as a `peerDependency` in libraries like `minanft`, for a reason unrelated to this one: Having multiple o1js versions around often breaks how o1js uses internal global state.

Now we have a new reason to recommend that :D It seems that having two different versions clash badly when using [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties).
TIL: TS compiles all private class members away but leaves a single opaque `#private` property.

This seems unpleasant, and I'm not really surprised -- I've seen a bunch of hard-to-understand type issues coming from private class fields already. Maybe I'll just give up on them 😆

**Comment by mitschabaude** [comment] 2023-12-14 15:01
Well - I confirmed that removing private properties from `Field`, `Bool`, `Group` and `Scalar` makes the problem go away, but only if I remove them in _both_ o1js versions

**Comment by mitschabaude** [comment] 2023-12-14 15:58
I'm removing private class fields on core types to improve this behaviour in the future: https://github.com/o1-labs/o1js/pull/1319

**Comment by mitschabaude** [comment] 2023-12-14 18:43
Closing because #1319 is merged and the only current fix is to not have multiple o1js versions

**Closed by mitschabaude** 2023-12-14 18:43 UTC
Labels: bug

**Comment by dfstio** [comment] 2023-12-15 12:02
@mitschabaude 
Thank you for pointing out the cause of the error, it was my fault: I forgot to change the o1js version in one of the package.json files.

I have two package.json files in the minanft library, one in the root folder and one in the dist folder that is intended for pushing compiled library to the npm.
`yarn upgrade-interactive' changes only the first one, and I forgot to change the second one.

I've fixed it and now everything is working as intended.

**Comment by iluxonchik** [comment] 2023-12-29 15:39
I'd also like to add that you should run `npm run build` after the upgrade. This fixed as similar problem that I was having on my side.
