### ISSUE TITLE
Compiling ZkProgram in the browser never ends

### ISSUE THREAD

**Issue by berkay1532** [o1-labs/o1js#1891] opened 2024-11-07 22:20 UTC
I noticed that a simple zkprogram I created did not compile in the browser. Then I tried to compile the zkprogram in the tutorial to see if the problem was with my program, but it did not compile either. Finally, when I removed the "**SelfProof**" parts in the zkprogram and compiled it, I saw that the process was completed without any problems. That's why I decided to open an issue about this.

Tutorial ZkProgram
`
const Add = ZkProgram({
  name: 'add-example',
  publicInput: Field,

  methods: {
    init: {
      privateInputs: [],

      async method(state: Field) {
        state.assertEquals(Field(0));
      },
    },

    addNumber: {
      privateInputs: [SelfProof, Field],

      async method(
        newState: Field,
        earlierProof: SelfProof<Field, void>,
        numberToAdd: Field
      ) {
        earlierProof.verify();
        newState.assertEquals(earlierProof.publicInput.add(numberToAdd));
      },
    },

    add: {
      privateInputs: [SelfProof, SelfProof],

      async method(
        newState: Field,
        earlierProof1: SelfProof<Field, void>,
        earlierProof2: SelfProof<Field, void>
      ) {
        earlierProof1.verify();
        earlierProof2.verify();
        newState.assertEquals(
          earlierProof1.publicInput.add(earlierProof2.publicInput)
        );
      },
    },
  },
});
`

**Comment by YofiY** [comment] 2024-11-09 14:55
I have been having the same issue.

**Comment by 45930** [comment] 2024-11-10 12:02
What version of o1js are you using?  Could you make sure it's either 1.9.1 or 2.0.0?

**Comment by berkay1532** [comment] 2024-11-10 12:23
Yes i tried both.Unfortunately neither worked.

**Comment by kadirchan** [comment] 2024-11-14 15:25
https://github.com/o1-labs/o1js/issues/1890#issuecomment-2469029108
can you try `"o1js": "https://pkg.pr.new/o1-labs/o1js@fc16ce3"`

**Comment by berkay1532** [comment] 2024-11-14 22:31
Finally, it's working! This problem took me about 10 days. Thank u @kadirchan.

**Comment by 45930** [comment] 2024-11-15 03:14
@berkay1532 , I don't think we can close this issue if the fix is to use a non-released version of o1js.  We still need to release a fixed version.

**Comment by berkay1532** [comment] 2024-11-15 16:26
Yep , i think so. Let’s not close till it is solved

**Comment by mitschabaude** [comment] 2024-11-18 19:30
It sounds like the fix is to use an older o1js version, so there was a recent regression?

**Comment by 45930** [comment] 2024-11-19 02:04
@mitschabaude we believe it's this one: https://github.com/o1-labs/o1js/pull/1874

Up to 1.9.0 compiling in the browser didn't work, then at exactly 1.9.0, when the pickles bug was fixed, but we introduced a performance issue, compilation in the browser _did_ work.  Then in 1.9.1 and the releases since, after we resolved the performance issue, it doesn't work in the browser again.

**Comment by mitschabaude** [comment] 2024-11-19 06:59
Oh interesting. What about our CI tests which compile in the browser though? Is there a more specific situation in which it doesn't work?

**Comment by mitschabaude** [comment] 2024-11-19 07:01
Ah it's only when using recursion. (Just like the performance regression!)

**Comment by mitschabaude** [comment] 2024-11-19 07:17
The performance regression happened in the recursive verifier.

Since #1874 fixed that regression, we can conclude that `maybe_lagrange_basis` is called in the recursive verifier.

Since this part now seems to break, a very likely issue is that the lagrange basis is not present in the recursive verifier. in the browser at least!

the browser case is different from nodejs at least in that there is no caching.
so it could be that the cache-miss case doesn't work in the browser. looking into it!

**Comment by mitschabaude** [comment] 2024-11-19 11:44
@45930 I identified and fixed the problem. It's on me 😅 

https://github.com/o1-labs/o1js-bindings/pull/313
https://github.com/o1-labs/o1js/pull/1906

**Closed** 2024-11-20 02:51 UTC

**Comment by kadirchan** [comment] 2024-11-24 15:06
upgraded mine from `"o1js": "https://pkg.pr.new/o1-labs/o1js@fc16ce3"` to `o1js 2.1` and it does not compiles recursive zkProgram anymore @45930 @mitschabaude 

[here is corresponding worker](https://github.com/DRM-Mina/drm-mina-web-client/blob/b5356298a578da10e505f0295d24636cca1a9d4f/ui/lib/worker.ts#L75)

**Comment by 45930** [comment] 2024-11-24 16:36
@kadirchan the fix has not been released yet.  It is scheduled for the next release, which ought to be this week.  You can check the [changelog](https://github.com/o1-labs/o1js/blob/main/CHANGELOG.md) for details

**Comment by kadirchan** [comment] 2024-11-24 17:27
oh I missed unreleased part sorry for inconvenience 🙏
